### ISSUE TITLE
Research Deployment options 

### ISSUE THREAD

**Issue by ToriCAST** [cast-fuse/gingerbread-tips#22]
links to #21

**Comment by andrewMacmurray** [comment]
Have had a look at this:

+ heroku is definitely the the most easily managed service (and decent enough free tier access)
+ aws is cheap but more maintenance required

Given the timescale on the project we have decided to go with the heroku option for now. If we need to deploy to aws at some point for whatever reason, we can reopen the issue.

http://gingerbread-tips.herokuapp.com/
