### ISSUE TITLE
Define taxonomies

### ISSUE THREAD

**Issue by ToriCAST** [cast-fuse/gingerbread-tips#25]
We need to define two taxonomies, that visible to GB users and the one visible to GB admins.

Links to #3 #6

**Comment by fayegoldman** [comment]
Taxonomy that's visible to parents: Money / Home / Legal / Safety / Your kids / Your ex / Coping / Support from others
Taxonomy that's visible to admins only: Unpublished / Published / Awaiting review / Approved for use
I think that's everything, but have done that super quickly so will get back to you asap if I realise I've missed something.

**Comment by fayegoldman** [comment]
Sorry - I missed one tag: Testimonial
