### ISSUE TITLE
Copy and title for microsite

### ISSUE THREAD

**Issue by ToriCAST** [cast-fuse/gingerbread-tips#33]
Links to #12

**Comment by fayegoldman** [comment]
@andrewMacmurray @ivanmauricio 
Just to note that the title and copy Simon used on his designs wasn't a final version. Are we ok to still update this on the microsite?

**Comment by fayegoldman** [comment]
@ivanmauricio @andrewMacmurray Copy for the top of the microsite main page: 

Trusted tips and tricks from single parents around the UK. Brought to you by Gingerbread.
