### ISSUE TITLE
Filter by tags in SPA

### ISSUE THREAD

**Issue by ivanmauricio** [cast-fuse/gingerbread-tips#38]
We need to work out implementation of tag filtering for SPA.

links #15

**Comment by fayegoldman** [comment]
@ivanmauricio @andrewMacmurray - the tags don't seem to be appearing properly on the microsite as it is. This might just be a temporary thing if you're working on other fixes. But for now everything is showing up as tagged as 'Separation' rather than the tags I assigned in Wordpress

**Comment by fayegoldman** [comment]
Also - can the tags under each quote also act as links to a filtered page, as well as the tags in the yellow banner?

**Comment by andrewMacmurray** [comment]
@fayegoldman yep they're just placeholders for now

**Comment by andrewMacmurray** [comment]
closed with pr #59
