### ISSUE TITLE
Heroku doesn't spin up in time for microsite

### ISSUE THREAD

**Issue by andrewMacmurray** [cast-fuse/gingerbread-tips#58]
When the first user visits the microsite the request fails (it says it's due to CORS which is confusing) but after the heroku app has spun up the microsite is able to fetch the data

We could have a look at extending the request timeout first but if this doesn't work it might be worth paying for the basic heroku service during the pilot phase

**Comment by andrewMacmurray** [comment]
So have had a look at extending the request time and this doesn't solve the problem. The problem seems to be that once the app spins down the rest api is not registered anymore, someone needs to go in and click on the permalinks section to activate it again (don't really understand why this makes it work 😕 ).

The bottom line however is that we'll probably need the Wordpress site to remain active which is possible on the hobby account for heroku, it's $7/month so shouldn't break the bank and can activate it during the testing phase.

https://www.heroku.com/pricing

**Comment by fayegoldman** [comment]
Ok. Thanks for clarifying @andrewMacmurray I'll check we're ok to pay that during testing, but like you said - it's not big money! Should be fine.

**Comment by andrewMacmurray** [comment]
solved this, we missed out the `.htaccess` file for the deployed site 🙃
